version: 0.2
phases:
  install:
    commands:
      - echo "installing dependencies..."
      - npm install
  build:
    commands:
      - echo "creating zip files..."
      - zip ./index.zip ./index.js && zip ./lambda_function.zip ./lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda function code..."
      - aws lambda update-function-code --function-name "github-cicd" --zip-file fileb://./index.zip
      - aws lambda update-function-code --function-name "khoi--Data" --zip-file fileb://./lambda_function.zip
      - aws lambda publish-version --function-name "github-cicd"
      - aws lambda publish-version --function-name "khoi--Data"
      - aws lambda invoke --function-name github-cicd --invocation-type Event --region us-west-1 response.json 
      - aws lambda invoke --function-name khoi--Data --invocation-type Event --region us-west-1 response_khoidata.json 
artifacts:
    files:
     - './appspec.json'
    discard-paths: yes
