# This is a basic workflow to help you get started with Actions

name: deploy to lambda

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #- name: npm install and build
       # run: |
       #   npm ci
        #  npm run build --if-present
        #env:
        #  CI: true
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq ./bundle.zip ./index.js && zip -qq ./bundlepython.zip ./prometheus.py
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-1
          function_name: github-cicd
          zip_file: ./bundle.zip
      - name: new deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-southeast-1
          function_name: khoi--Data
          zip_file: ./bundlepython.zip
